### ISSUE TITLE
ReadMe needs to be updated to include some known errors

### ISSUE THREAD

**Issue by dmarlingSplunk** [paychex/Splunk.Conf19#3]
Per my conversation with @JykkeDaMan on splunk answers, https://answers.splunk.com/answers/780617/paychexsplunkconf19-cover-your-assets-cya-export-e.html, We need to update the readme with language that explains it is safe to ignore the "Failed to parse templatized search for field" errors for any field that the beginning of it is named "tagged.*" and that is originating from the ntags end point.

**Comment by efav** [comment]
Readme has been updated.
