### ISSUE TITLE
When importing to lookup, error indicates - File has no line endings

### ISSUE THREAD

**Issue by dimarra** [paychex/Splunk.Conf19#6]
Encountered the following error while trying to save: File has no line endings.

The first line is quite long.  Not sure if this is the reason.  Is there a proper way to save it from the export step?

I am unable to import the csv.

Importing on
Splunk Enterprise
Version: 8.0.5
Build: a1a6394cc5ae

**Comment by dmarlingSplunk** [comment]
Hi @dimarra,

How and where are you saving the file when you export it?  Are you making it a lookup in splunk or are you saving it somewhere on a machine?

**Comment by efav** [comment]
@dimarra Last chance before we close this due to time elapsed.

**Comment by efav** [comment]
Closing issue due to lack of response.
